In [1]:
# https://medium.com/emergent-future/simple-reinforcement-learning-with-tensorflow-part-0-q-learning-with-tables-and-neural-networks-d195264329d0
import gym
import numpy as np

In [2]:
env = gym.make('FrozenLake-v0')

In [5]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []

In [6]:
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [9]:
print ("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.6055


In [11]:
print ("Final Q-Table Values")
print (Q)

Final Q-Table Values
[[2.08643709e-01 6.15232349e-03 7.97205835e-03 8.08176201e-03]
 [1.24479079e-03 8.22053765e-04 1.14470985e-03 1.53007807e-01]
 [1.45887393e-01 9.24494223e-04 7.25911509e-03 5.53441121e-03]
 [9.17960188e-04 1.30894746e-03 1.89471575e-04 1.36893008e-02]
 [2.02137517e-01 3.58026832e-03 5.84422783e-03 3.00333578e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.44809776e-01 2.31539512e-05 2.04856262e-04 3.02403338e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.14813259e-02 1.28773280e-03 1.66953500e-03 5.28219004e-01]
 [3.77067979e-03 7.22557644e-01 2.40519009e-03 5.93862345e-03]
 [7.30981231e-01 0.00000000e+00 5.46208344e-04 1.01972048e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 8.81216549e-01 1.24363394e-03]
 [0.00000000e+00 9.92521027e-01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.